<?php 
/**
 * Ultimate_AjaxProductSort extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Ultimate
 * @package		Ultimate_AjaxProductSort
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Sort list template on product page
 *
 * @category	Ultimate
 * @package		Ultimate_AjaxProductSort
 * @author Ultimate Module Creator
 */
?>
<?php $sorts = $this->getSortCollection();?>
<?php if ($sorts->count() > 0) :?>
<div class="box-collateral box-sorts box-up-sell">
	<?php foreach ($sorts as $sort) : ?>
		<div class="item">
			<a href="<?php echo $sort->getSortUrl()?>">
				<?php echo $sort->getColor();?><br />
			</a>
		</div>
	<?php endforeach; ?>
</div>
<?php endif;?>