<?php 
/**
 * Ultimate_AjaxProductSort extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Ultimate
 * @package		Ultimate_AjaxProductSort
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Sort view template
 *
 * @category	Ultimate
 * @package		Ultimate_AjaxProductSort
 * @author Ultimate Module Creator
 */
?>
<?php $_sort = $this->getCurrentSort();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title sort-title">
	<h1><?php echo $_sort->getColor(); ?></h1>
</div>
<div class="sort-view">

</div>