<?php
/**
 * Ultimate_AjaxProductSort extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Ultimate
 * @package		Ultimate_AjaxProductSort
 * @copyright  	Copyright (c) 2013
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Sort link widget template
 *
 * @category	Ultimate
 * @package		Ultimate_AjaxProductSort
 * @author Ultimate Module Creator
 */
?>
<?php $_sort = $this->getCurrentSort();?>
<?php if ($_sort) :?>
	<div class="sort-widget-link">
		<a href="<?php echo $_sort->getSortUrl()?>"><?php echo $_sort->getColor()?></a>
	</div>
<?php endif;?> 